CC=g++
CFLAGS=-std=c++11 
LDFLAGS=-lncurses

all: layout

layout_new: main_new.cpp layout_new.cpp layout_new.hpp
	$(CC) $(CFLAGS) main_new.cpp layout_new.cpp layout_new.hpp -o layout_new $(LDFLAGS)

